### ISSUE TITLE
Different EOF error exceptions

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct_javascript_runtime#1]
Currently, in JavaScript runtime, reading more bytes than there are in the stream using `readBytes(...)` results in `KaitaiEOFError` being thrown.
However, doing the same (i.e. reading past end of buffer) with other primitive reading functions, such as `readU4le()`, results in `RangeError: Offset is outside the bounds of the DataView`.

Shall we make it straight and uniform and fix it to adhere to the same standard (for example, `RangeError` everywhere)?

**Comment by cherue** [comment]
This has been fixed in a019595a177ce40636e26492b1a0d55c68582728 and can be closed.

**Comment by GreyCat** [comment]
Thanks for checking, closing :)
