### ISSUE TITLE
BigInt support

### ISSUE THREAD

**Issue by cherue** [kaitai-io/kaitai_struct_javascript_runtime#13]
[BigInts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) are now a thing in JS. They're supported in modern browsers and Node 10.4 and higher.

From MDN:
> BigInt is similar to Number in some ways, but also differs in a few key matters — it cannot be used with methods in the built-in Math object and cannot be mixed with instances of Number in operations; they must be coerced to the same type.

I think this would mean two runtimes and two compiler targets. Because the KS expression language allows math that gets translated into JS and all the read integers must be the same type, either `BigInt` or `Number`, no mixing allowed.
And on the compiler side if there is an expression like `offset + 4` we need to know at compile time whether to do `4` (Number) or `4n` (BigInt).

Another option with one runtime and target would be to wrap everything that could turn into a number with a function that turns numbers into bigints if required. Seems like it wouldn't be very readable, might work with a very short name though.

**Comment by generalmimon** [comment]
There is already an issue tracking this: https://github.com/kaitai-io/kaitai_struct/issues/183

This enhancement probably doesn't concern just the runtime library, so I'd suggest closing this issue and continue in the existing issue.

**Comment by GreyCat** [comment]
Makes sense. @cherue, can you clarify if your intent is 64-bit integer support or true BigInt support? If it's the former, probably we should go to https://github.com/kaitai-io/kaitai_struct/issues/183, otherwise I will transfer it as a separate issue.

**Comment by cherue** [comment]
I wasn't aware of that issue, I'll repost there and close this.
