### ISSUE TITLE
Add package.json

### ISSUE THREAD

**Issue by raymond-h** [kaitai-io/kaitai_struct_javascript_runtime#2]
As of right now this runtime is impossible to install using npm. Adding a `package.json` file will allow npm to install it straight from the Github repo.

Even better would be to also publish the runtime to npm as well.

**Comment by GreyCat** [comment]
@koczkatamas recently made an npm release: https://www.npmjs.com/package/kaitai-struct

Could you take a look and see if that would work for you?

**Comment by raymond-h** [comment]
Looks perfect to me! Now the main compiler should use this module also in CommonJS environments (to resolve kaitai-io/kaitai_struct#180), which I have started working on.
