### ISSUE TITLE
Error in error handling -- no terminator found in string message.

### ISSUE THREAD

**Issue by theorbtwo** [kaitai-io/kaitai_struct_javascript_runtime#5]
https://github.com/kaitai-io/kaitai_struct_javascript_runtime/blob/22754e0c534e534a993c22172b42f0dd7297a208/KaitaiStream.js#L461
Tiny little error: that "term" should be "terminator"

**Comment by GreyCat** [comment]
True enough. Thanks!

**Comment by GreyCat** [comment]
Should be fixed now.
